const TRIP_EVENTS = {
  '2026-05-01': [
    { time:'11:20', end:'12:30', name:'Land at Cusco Airport', desc:'TreXperience driver waiting at arrivals. Clear immigration + collect bags (~75 min).', type:'logistics',
      place:'Cusco Airport (CUZ)',
      facts:['Cusco Airport sits at 3,399m — one of the highest commercial airports in the world!','The word "Cusco" in Quechua means "Navel of the World" — the Incas believed it was the center of the universe.','Your body needs 24–48 hrs to adjust to the altitude here. Drink lots of water and go slow!','Coca tea is served everywhere in Cusco — it helps with altitude sickness and tastes like green tea.','The Inca Empire was the largest empire in pre-Columbian America, stretching 4,300 km along the Andes.','Cusco was the capital of the Inca Empire from the 13th century until Spanish conquest in 1533.','The city was deliberately built in the shape of a puma — a sacred animal in Inca culture.','Quechua, the language of the Incas, is still spoken by over 8 million people today.','Cusco receives about 2 million tourists every year — more than any other city in Peru.','The average temperature in Cusco in May is a cool 18°C (64°F) during the day and near freezing at night.']
    },
    { time:'12:30', end:'15:07', name:'Drive to Ollantaytambo', desc:'Private van ~1.5 hrs. Drop checked bag at PeruRail free storage. Quick lunch in town.', type:'logistics',
      place:'Sacred Valley',
      facts:['The Sacred Valley stretches 60km between Cusco and Machu Picchu along the Urubamba River.','The Incas grew over 3,000 varieties of potato in the Sacred Valley — yes, 3,000!','The valley sits 600m lower than Cusco, so the air feels noticeably easier to breathe here.','Incan farmers built terraces (called "andenes") to farm steep hillsides — some are still used today.','The Urubamba River flowing through the valley was called "Willkamayu" — meaning "Sacred River" in Quechua.','The Sacred Valley was chosen by the Incas for its perfect farming climate and spiritual energy.','You might spot condors soaring above the valley — they have a wingspan of up to 3.2 meters!','Local women in the valley still wear traditional colorful clothing called "polleras" every day.','The valley produces the best corn (choclo) in Peru — the kernels are giant compared to regular corn.','Archaeologists are still discovering new Inca ruins hidden in the mountains of the Sacred Valley.']
    },
    { time:'15:07', end:'15:37', name:'Board train at Ollantaytambo', desc:'PeruRail Vistadome Observatory 603. Be on the platform 30 min before departure.', type:'logistics',
      place:'Ollantaytambo',
      facts:['Ollantaytambo is the only Inca town in Peru still inhabited by people living in original Inca buildings!','The fortress of Ollantaytambo was one of the few places where the Incas successfully defeated the Spanish conquistadors.','The town was built in the shape of a maize cob — corn was sacred to the Incas.','Water channels built by the Incas 600 years ago still run through the streets of Ollantaytambo today.','The massive stone blocks in the temple were quarried from a mountain 6km away and across the river!','Ollantaytambo means "Resting place of Ollanta" — named after a legendary Inca general.','The town has had running water since Inca times — one of the oldest water systems in the Americas.','Local kids play football (soccer) in the same plaza where Inca ceremonies were held 500 years ago.','The ruins at Ollantaytambo were used as a filming location for the movie "The Motorcycle Diaries".','You can still see the original Inca walls lining the narrow streets — the Spanish built on top of them.']
    },
    { time:'15:37', end:'17:02', name:'Train to Aguas Calientes', desc:'Panoramic cloud forest journey. Arrives Machu Picchu Pueblo station 17:02.', type:'afternoon',
      place:'Cloud Forest Railway',
      facts:['The train descends over 1,500m in just 1.5 hours — one of the most dramatic rail journeys on Earth!','The cloud forest you are passing through is home to over 300 species of orchid.','This valley is so narrow that the train tracks were built right next to the rushing Urubamba River.','The cloud forest produces its own rain — clouds get trapped by the mountains and release moisture constantly.','You might spot a torrent duck on the river rocks — they are one of the few birds that swim in rapids.','The Vistadome glass roof lets you see the mountain peaks towering straight above the train.','The transition from Andes to Amazon happens right here — watch the vegetation change as you descend!','Spectacled bears (the inspiration for Paddington Bear!) live in these cloud forests.','The cloud forest here is one of the most biodiverse ecosystems on the planet.','Machu Picchu was only connected to Cusco by rail in 1948 — before that, it was only reachable on foot.']
    },
    { time:'17:02', end:'18:30', name:'Arrive & check in — Casa Andina', desc:'Ask hotel about Ministry of Culture opening time tomorrow. Request early May 3 breakfast.', type:'logistics',
      place:'Aguas Calientes',
      facts:['Aguas Calientes means "Hot Waters" in Spanish — named after the natural hot springs here.','The town only has about 3,000 permanent residents but receives over 1 million tourists per year!','There are no roads to Aguas Calientes — the only way in is by train or a 2-day hike.','The town sits inside a deep gorge with mountains rising 2,000m on both sides — it feels like the bottom of the world.','The Urubamba River rushing through town is one of the fastest rivers in Peru.','Aguas Calientes was almost completely destroyed by a mudslide in 2010 — it was rebuilt from scratch.','The town square has a statue of Pachacutec — the Inca emperor who built Machu Picchu.','Every shop, hotel, and restaurant in town exists entirely because of Machu Picchu.','The natural hot springs here reach 40°C (104°F) — perfect for sore legs after hiking!','At night, the mountains surrounding the town are completely dark — no light pollution, incredible stars.']
    },
    { time:'18:30', end:'19:30', name:'Ministry of Culture — Chance #1', desc:'Check if office still open on Av. Pachacutec. If open, buy Circuit 2 tickets for May 3 now.', type:'priority',
      place:'Aguas Calientes',
      facts:['Machu Picchu only allows 4,044 visitors per day — it used to be unlimited and the site was being damaged!','The Ministry of Culture controls all Machu Picchu tickets to protect the ancient stones from overuse.','Circuit 2 is the most popular route — it includes the iconic viewpoint seen on every postcard.','Tickets are personal — your name is printed on each one and must match your passport exactly.','The site was divided into circuits in 2019 to reduce crowding at specific viewpoints.','Getting tickets in person in Aguas Calientes is the secret move most tourists do not know about.','Peak season in May means tickets can run out — being first in line on May 2 morning is essential.','Each circuit takes 2–4 hours depending on your pace and how many photos you take!','Machu Picchu gets about 1.5 million visitors per year — managed carefully to protect the stones.','The ticket price has increased significantly in recent years to fund conservation of the site.']
    },
    { time:'19:30', end:'21:00', name:'Dinner — TUNAWA Andean Fusion', desc:'Rated 4.8. Laguna ceviche, pollo saltado. 5-min walk from plaza. Early night!', type:'evening',
      place:'Aguas Calientes',
      facts:['Aguas Calientes means "Hot Waters" in Spanish — named after the natural hot springs here.','The town only has about 3,000 permanent residents but receives over 1 million tourists per year!','There are no roads to Aguas Calientes — the only way in is by train or a 2-day hike.','The town sits inside a deep gorge with mountains rising 2,000m on both sides.','The Urubamba River rushing through town is one of the fastest rivers in Peru.','Aguas Calientes was almost completely destroyed by a mudslide in 2010 — it was rebuilt from scratch.','The town square has a statue of Pachacutec — the Inca emperor who built Machu Picchu.','Every shop, hotel, and restaurant in town exists entirely because of Machu Picchu.','The natural hot springs here reach 40°C (104°F) — perfect for sore legs after hiking!','At night, the mountains surrounding the town are completely dark — incredible stars overhead.']
    },
    { time:'21:00', end:'23:59', name:'Sleep — alarm set for 5:30am', desc:'Lower altitude means great sleep for everyone.', type:'logistics',
      place:'Aguas Calientes',
      facts:['Sleeping at 2,040m altitude is much easier than Cusco\'s 3,400m — you chose wisely!','Your body repairs itself during sleep — especially important before a big mountain hike tomorrow.','The sound of the Urubamba River rushing past the town creates a natural white noise — great for sleeping.','Machu Picchu at sunrise (6am) has misty clouds rolling through the ruins — the most magical sight in South America.','The early bus queue starts at 5am — being among the first on the mountain means fewer crowds.','Tomorrow is the big day — Machu Picchu at sunrise on a birthday! Rest well.','The temperature drops significantly at night in the gorge — use all the hotel blankets!','Machu Picchu faces east, so the sunrise hits the ruins directly from the front — stunning golden light.','The Incas deliberately oriented Machu Picchu to align with the rising sun during the solstice.','You are less than 8km from one of the Seven Wonders of the World right now!']
    },
  ],
  '2026-05-02': [
    { time:'05:00', end:'05:30', name:'Guide meets at hotel', desc:'TreXperience guide accompanies family to the Ministry of Culture queue.', type:'priority',
      place:'Aguas Calientes',
      facts:['Licensed Machu Picchu guides must pass a rigorous government exam — they know every stone!','Your TreXperience guide speaks English and Quechua — the original language of the Incas.','A good guide transforms Machu Picchu from "old rocks" to a living, breathing Inca city story.','Guides are legally required inside Machu Picchu — solo exploration without one is not permitted.','Many guides are descendants of the Quechua people who built Machu Picchu — history runs in their blood.','TreXperience guides are trained to do "Inca treasure hunts" for kids — your 8-year-old will love it!','Your guide knows exactly which viewpoints get the best photos at which times of day.','The best guides bring snacks, know all the shortcuts, and make sure no one gets left behind.','A bilingual guide costs about the same as a nice dinner — and is worth 10x more for the experience.','Your guide today will also help you navigate the Ministry of Culture — that alone is priceless.']
    },
    { time:'05:30', end:'07:00', name:'Queue — Ministry of Culture', desc:'All 3 family members with passports. Token distribution starts at 6am on Av. Pachacutec.', type:'priority',
      place:'Aguas Calientes',
      facts:['The Ministry of Culture distributes numbered tokens from 6am — get yours early for the best pick!','Ticket sales open at 3pm same day — your token number holds your place in the queue.','All 3 family members should be present with passports — each ticket is personal and non-transferable.','Pay in exact Peruvian Soles cash only — approximately 152 soles per adult. No change given!','The 3pm ticket window can sell out of popular circuits — Circuit 2 goes fastest.','Locals call the ticket office the "Casa de la Cultura" — easy to find on Av. Pachacutec.','Morning light in Aguas Calientes is beautiful — the mist in the gorge looks like something from a movie.','The queue at 5:30am is quiet and peaceful — most tourists are still asleep in their hotels.','Your guide\'s presence in the queue means you will know exactly what to ask for when the window opens.','After getting your tokens, the whole day is free — waterfalls and thermal baths await!']
    },
    { time:'07:00', end:'09:00', name:'Hotel breakfast', desc:'Tokens secured! Eat well. Build excitement with the kid for tomorrow at Machu Picchu.', type:'morning',
      place:'Aguas Calientes',
      facts:['A proper breakfast before a hike is crucial — protein and carbs give you energy for hours.','Peruvian breakfast often includes pan (fresh bread), fresh fruit juice, and eggs.','Quinoa porridge is a local breakfast staple — quinoa has been grown in the Andes for 5,000 years!','Fresh passion fruit juice (maracuyá) is found everywhere in Peru — try it if you haven\'t!','Peruvians drink mate de coca (coca leaf tea) every morning — it helps with energy and altitude.','The coca plant used in tea is completely legal in Peru — it has been used medicinally for 4,000 years.','Tomorrow\'s 4:30am wake-up means tonight you need to be in bed by 8:30pm at the latest.','Eating a big breakfast now means you can pack lighter snacks for the Machu Picchu hike tomorrow.','Your 8-year-old should eat plenty of carbs today — they need extra energy for tomorrow\'s adventure.','The hotel breakfast view of the misty gorge in the morning is absolutely stunning — take a photo!']
    },
    { time:'09:00', end:'12:30', name:'Waterfalls — Mandor or Alcamayo', desc:'Option A: Mandor sanctuary (45-min walk along tracks). Option B: Alcamayo pools (20-min walk).', type:'morning',
      place:'Aguas Calientes & Waterfalls',
      facts:['The Mandor Waterfall sanctuary is one of the best-kept secrets near Machu Picchu — most tourists never find it!','The walk to Mandor follows the active train tracks — trains are very slow and loud here, completely safe.','Mandor sanctuary has over 50 species of orchid — some only bloom once a year.','On a clear day, you can see the peak of Machu Picchu mountain from the Mandor viewpoint!','Alcamayo waterfall feeds two natural swimming pools — the water is cold but refreshing.','The cloud forest around both waterfalls has butterflies the size of your hand!','Spectacled bears have been spotted near Mandor sanctuary — they are very shy and harmless.','The sound of both waterfalls is so loud you have to shout to talk to each other nearby!','Both waterfalls are completely free from crowds — a rare thing this close to Machu Picchu.','The walk along the train tracks passes local farms where you can buy fresh fruit directly.']
    },
    { time:'12:30', end:'14:00', name:'Lunch — Ayahuasca Grill', desc:'Rated 4.9. Walk uphill away from tourist strip. Best trout and chicken in Aguas Calientes.', type:'afternoon',
      place:'Aguas Calientes',
      facts:['Trucha (Andean trout) is the signature dish of Aguas Calientes — the fish comes from mountain rivers.','The Andean trout is not native to Peru — it was introduced from North America but thrived in cold mountain rivers.','Peruvian cuisine was voted the World\'s Best Culinary Destination for 8 consecutive years!','Lomo saltado (stir-fried beef or chicken) is Peru\'s most beloved home-cooking dish.','Ají amarillo — yellow chilli — is the backbone of Peruvian cooking. Not too spicy, very aromatic.','Peru has 3,000+ varieties of potato and 55 varieties of corn — all originally from the Andes.','Ceviche, Peru\'s national dish, was actually invented on the Pacific coast — not up here in the mountains.','Restaurants uphill from the train station are always better and cheaper than tourist-strip spots.','Chicha Morada (purple corn drink) is a uniquely Peruvian drink — sweet, refreshing, and full of antioxidants.','The best meal you eat in Peru will probably not be in a famous restaurant — it\'ll be a hidden local spot!']
    },
    { time:'14:00', end:'14:45', name:'Thermal baths', desc:'Pre-Machu Picchu soak. ~15 soles. Bring towel + flip-flops.', type:'afternoon',
      place:'Aguas Calientes Hot Springs',
      facts:['The hot springs reach 40°C (104°F) — naturally heated by volcanic activity deep underground!','Hot springs have been used by Andean people for healing and relaxation for over 2,000 years.','The mineral-rich water is said to help with muscle soreness — perfect before a mountain hike.','There are multiple pools at different temperatures — try starting in a warm one and moving hotter.','The springs are at the base of a forested cliff — the setting is dramatic and beautiful.','Bring flip-flops — the pool floors can be slippery and shared footwear is not allowed.','The springs are busiest between 11am–1pm — you are going at the perfect quiet time.','Local Quechua people believe the hot springs have medicinal properties for joints and skin.','The water flowing into the pools comes directly from natural underground springs in the mountain.','Soaking in hot springs at altitude is very relaxing — your legs will thank you tomorrow!']
    },
    { time:'14:45', end:'16:30', name:'⚠️ Return — Ministry of Culture 3pm', desc:'BE THERE BY 2:45PM SHARP. Tickets on sale at 3pm. Pay EXACT soles cash — no change given.', type:'priority',
      place:'Aguas Calientes',
      facts:['The Ministry of Culture ticket window opens at exactly 3pm — numbers are called in batches, not strict order.','Being late (even 10 minutes) can mean missing your batch and waiting much longer.','Ask specifically for "Circuit 2, 6am entry, May 3" — be clear and direct at the window.','Each ticket is printed with your name and passport number — they match your ID at 3 checkpoints.','The daily capacity of 4,044 visitors is divided across all circuits — Circuit 2 is most popular.','If Circuit 2 is sold out, Circuit 1 is equally spectacular — maybe even better views!','Once you have the tickets in hand, take a photo of them immediately as backup.','Check every detail on the ticket: name spelling, date, circuit number, entry time.','The ticket is valid only for the exact date and entry time slot printed on it — no flexibility.','Having your guide present at the window makes this whole process smooth and stress-free.']
    },
    { time:'16:30', end:'19:00', name:'Town stroll + artisan market', desc:'Manco Capac Square. Buy kid a Machu Picchu souvenir to build excitement for tomorrow.', type:'afternoon',
      place:'Aguas Calientes',
      facts:['Manco Capac was the legendary first Inca emperor — said to have emerged from Lake Titicaca with his sister.','The artisan market sells hand-woven alpaca products — alpaca wool is softer than cashmere!','Alpaca sweaters and scarves sold here are made using techniques passed down for over 500 years.','Real alpaca wool is odor-resistant, hypoallergenic, and warmer than sheep wool.','Bargaining is completely normal and expected in Peruvian markets — start at 50% of asking price.','The best souvenir from Peru is a hand-woven textile — each pattern tells a story about its maker\'s community.','Children in Peru often help their families weave textiles — it is a skill learned from age 5 or 6.','The colors in Andean textiles come from natural dyes made from plants, insects, and minerals.','A small Machu Picchu keychain or llama stuffed animal makes a perfect souvenir for a young explorer.','The plaza at dusk fills with local families, street food vendors, and the sound of the river below.']
    },
    { time:'19:00', end:'20:30', name:'Dinner — Mistura restaurant', desc:'Rated 4.7. River views. Mention tomorrow is a birthday! Pack bags tonight for 4:30am start.', type:'evening',
      place:'Aguas Calientes',
      facts:['Aguas Calientes means "Hot Waters" in Spanish — named after the natural hot springs here.','Tonight is the last calm evening before the biggest adventure of the trip — enjoy it slowly.','Packing your Machu Picchu daypack tonight means no rushing in the dark at 4:30am tomorrow.','Each person\'s daypack for tomorrow should have: 1L water, snacks, sunscreen, light jacket, passport, ticket.','The sunrise entry at 6am means you will be on the mountain before most tourists are even awake.','The mist at Machu Picchu in the morning is caused by warm humid air rising from the Amazon below.','Tomorrow\'s birthday moment at Machu Picchu will be one of the most memorable mornings of your lives.','Set two alarms for 4:30am — the bus queue starts at 5am and you want to be near the front.','The last bus back from Machu Picchu leaves at 5:30pm — you will be back well before that.','Peruvian restaurants always appreciate when you mention special occasions — expect a surprise!']
    },
    { time:'20:30', end:'23:59', name:'Sleep — alarm set for 4:30am', desc:'The first bus gets you on the mountain at sunrise. That is the moment you came for.', type:'logistics',
      place:'Aguas Calientes',
      facts:['Machu Picchu at sunrise is genuinely one of the most beautiful sights on Earth — worth every early alarm.','The site opens at 6am — first entry visitors get golden light, cool air, and almost no crowds.','The iconic postcard photo viewpoint (terraces + mountain) is about 10 minutes into Circuit 2.','In May, the site is lush and green from the rainy season — the most photogenic time of year.','Llamas and alpacas roam freely inside Machu Picchu — they are used to keep the grass trimmed!','The Incas built Machu Picchu in just 60–70 years — an extraordinary feat with only hand tools.','No wheels, no iron tools, no mortar — every stone was placed by hand and fits perfectly.','Machu Picchu was abandoned around 1572 and forgotten by the outside world for 350 years.','Hiram Bingham III "rediscovered" the site in 1911 — but local people always knew it was there.','Tomorrow at 6am you will stand where Inca royalty stood 500 years ago. Sleep well — big day!']
    },
  ],
  '2026-05-03': [
    { time:'04:30', end:'05:15', name:'Wake up + breakfast', desc:'Full breakfast — protein and carbs. Pack: 1L water each, snacks, sunscreen, rain jacket, passports, tickets.', type:'logistics',
      place:'Aguas Calientes',
      facts:['Today is the birthday AND Machu Picchu day — possibly the most special morning of the trip!','Eating a full breakfast now is crucial — the high altitude burns energy much faster than at sea level.','Machu Picchu sits at 2,430m — lower than Cusco but still high enough to feel altitude effects during activity.','The bus ride up takes 20 minutes on a winding road with 13 hairpin turns — sit by the window!','May is technically the shoulder season — the site is green, not too crowded, and weather is mostly clear.','The UNESCO World Heritage Site was designated in 1983 — it is protected as a global treasure.','Sunscreen is essential at Machu Picchu — altitude means much stronger UV rays than at sea level.','The light at 6am on the ruins creates an orange-gold glow that photographers call "the golden hour."','Your 8-year-old is about to experience something they will tell their own children about one day.','Happy birthday! What a day to celebrate — sunrise at a Wonder of the World.']
    },
    { time:'05:15', end:'06:00', name:'Consettur bus queue', desc:'Join queue by 5:15am. Buy round-trip bus tickets (~$24/adult). 20-min drive up the mountain.', type:'logistics',
      place:'Aguas Calientes',
      facts:['The Consettur bus company has been running the route to Machu Picchu since 1948!','The road up has 13 hairpin switchbacks — locals call it the "zig-zag road" and it is quite the ride.','Looking down from the bus window you can see the Urubamba River far below — a 400m drop!','The bus passes through cloud forest on the way up — sometimes in total mist, sometimes crystal clear.','On the drive up you might spot the "Drawing" — an Inca staircase carved into the mountainside.','The bus takes about 20 minutes — walking up on foot takes about 1 hour and 1,700 steps.','Locals sometimes run alongside the road to greet arriving buses — a fun tradition!','The bus queue at 5am feels adventurous — everyone is excited and bundled up in the cool morning air.','Round-trip bus tickets save you from the steep hike back down on tired legs after a long morning.','First light hits the peaks above Machu Picchu around 5:30am from the valley — look up on the bus!']
    },
    { time:'06:00', end:'09:30', name:'🎂 Enter Machu Picchu — Birthday!', desc:'Sunrise mist over the terraces. Golden light on Huayna Picchu. Llamas everywhere. TreXperience guide with Inca treasure hunt for the 8-year-old.', type:'birthday',
      place:'Machu Picchu',
      facts:['Machu Picchu means "Old Mountain" in Quechua — the peak towering behind it is called "Young Mountain."','The site has 200 buildings, 3,000 stone steps, and over 100 stairways — all built without mortar!','The stones fit so perfectly that you cannot slide a piece of paper between them — Inca stonework is that precise.','Machu Picchu was built around 1450 AD for Inca Emperor Pachacutec — it was his royal estate.','The Incas did not have wheels, iron tools, or a written language — yet they built this!','Machu Picchu is aligned with the sun — the Intihuatana stone was used as an astronomical calendar.','The llamas you see roaming the site are not wild — they are working animals that keep the grass trimmed.','Only about 40–50 people actually lived at Machu Picchu permanently — most were priests and staff.','The site was abandoned suddenly in the 1500s — no one knows exactly why it was left.','Machu Picchu was voted one of the New Seven Wonders of the World in 2007 by 100 million voters!']
    },
    { time:'09:30', end:'10:30', name:'Free time inside the citadel', desc:'Sit, breathe, let the kid explore near the llamas. No re-entry once you exit — plan bathroom breaks.', type:'afternoon',
      place:'Machu Picchu',
      facts:['The classic postcard photo spot is near the Guardian\'s House — your guide will take you there.','Look for the Temple of the Sun — its windows align perfectly with the winter solstice sunrise.','The Intihuatana stone was used by Inca priests to "tie the sun" during the solstice ceremonies.','Machu Picchu has its own microclimate — it can be sunny at the entrance and rainy at the far end!','The terraces you see were not just decorative — they were sophisticated drainage systems to prevent landslides.','More than 30% of the effort building Machu Picchu went underground — drainage, foundations, and retaining walls.','The Temple of the Condor has a rock shaped exactly like a condor in flight — it is mind-blowing when you see it.','Clouds roll in most afternoons, so morning entry always gives the clearest skies and best photos.','The view from the Guardian\'s House is the exact image on every Machu Picchu postcard — go there!','Sitting quietly for 5 minutes inside Machu Picchu and just breathing it in is something you will never forget.']
    },
    { time:'10:30', end:'12:00', name:'Bus back to Aguas Calientes', desc:'Return to Casa Andina. Shower and change. Leave main bags at reception for storage.', type:'logistics',
      place:'Aguas Calientes',
      facts:['The bus ride back down is faster than going up — the driver knows every curve by heart!','After 3–4 hours at Machu Picchu, your legs will feel it — the thermal baths are perfectly timed.','Casa Andina will store your bags all day after checkout — no need to lug them to the thermal baths.','The temperature in Aguas Calientes feels warm after the cool mountain air of Machu Picchu.','Today is May 3rd — birthday + Machu Picchu + thermal baths + birthday dinner in Cusco. What a day!','The Urubamba River sounds especially soothing after the excitement of the mountain this morning.','Aguas Calientes has a little chocolate shop near the plaza that makes Peruvian dark chocolate — outstanding.','A cold glass of chicha morada (purple corn drink) in Aguas Calientes after Machu Picchu is perfection.','The train back through the cloud forest this afternoon will feel completely different after the morning you have had.','Take a moment to celebrate — you just did Machu Picchu at sunrise on a birthday. That is extraordinary.']
    },
    { time:'12:00', end:'14:00', name:'Thermal baths — birthday recovery', desc:'Sore legs, happy hearts. 15 soles. Kid splashes, adults decompress. Best feeling of the trip.', type:'birthday',
      place:'Aguas Calientes Hot Springs',
      facts:['The thermal baths after a Machu Picchu morning are one of the best feelings in all of travel!','Warm water at 40°C relaxes muscles that have been climbing stone steps since 6am.','The mineral content of the springs includes magnesium and calcium — both great for muscle recovery.','Local Quechua people have soaked in these springs for centuries as a healing ritual.','The springs are fed by underground volcanic activity in the Andes mountain range.','Today is the birthday girl\'s turn to relax — the thermal baths are the perfect birthday treat.','Children love the thermal baths — the water is warm, the setting is dramatic, and there are multiple pools.','After the thermal baths, most people feel ready for a proper meal and a long comfortable journey home.','The sound of the waterfall feeding one of the pools creates a natural spa soundtrack.','Soaking in natural hot springs at the base of the Andes — this does not happen every birthday!']
    },
    { time:'14:00', end:'19:30', name:'Return train + taxi to Cusco', desc:'Pick up stored bags from Casa Andina reception. Board return train. TreXperience private taxi waiting at Ollantaytambo to drive to Cusco (~1.5 hrs).', type:'logistics',
      place:'Cloud Forest to Cusco',
      facts:['The return train journey feels completely different now — you are leaving as someone who has seen Machu Picchu!','The cloud forest looks magical in the afternoon light — golden rays cut through the mist between the trees.','As the train climbs back toward the Sacred Valley, the vegetation changes from jungle back to Andean grasses.','Your TreXperience taxi driver will be waiting at Ollantaytambo — no waiting, direct to your Cusco hotel.','The 1.5 hour drive back to Cusco passes through the Sacred Valley as the sun sets on the Andes — beautiful.','Arriving in Cusco tonight means sleeping at 3,400m altitude — drink lots of water to help acclimatize.','The birthday dinner at Morena Kitchen awaits — a window table overlooking the illuminated Plaza de Armas.','Cusco at night is magical — the plaza is lit up and the energy of the city is alive and warm.','Today has been: 4:30am wake-up, Machu Picchu at sunrise, thermal baths, train, taxi, birthday dinner. Legendary.','The Plaza de Armas in Cusco was the ceremonial heart of the Inca Empire — 500 years of history below your table.']
    },
    { time:'19:30', end:'20:30', name:'Arrive Cusco + hotel check-in', desc:'TreXperience driver drops at Cusco hotel. Freshen up for the birthday dinner.', type:'logistics',
      place:'Cusco',
      facts:['Cusco at night is one of the most beautiful cities in South America — warm lights on colonial stone walls.','The Plaza de Armas at night is surrounded by illuminated colonial buildings built directly on Inca foundations.','Cusco sits in a natural bowl surrounded by mountains — at night the city lights reflect off the hillsides.','The altitude at 3,400m means you should drink water and avoid alcohol on your first night back here.','Cusco\'s historic center is a UNESCO World Heritage Site — the whole old town is a living museum.','You can literally see Inca stonework on the ground floors of colonial buildings throughout the city.','The famous 12-angled stone in Hatunrumiyoc Street fits perfectly with all 12 surrounding stones — no mortar.','Cusco has over 200 colonial churches built by the Spanish — many on top of original Inca temples.','The city has been continuously inhabited for over 3,000 years — one of the oldest cities in the Americas.','Tonight you celebrate a birthday in the former capital of the greatest empire in the Americas. Extraordinary.']
    },
    { time:'20:30', end:'22:30', name:'🎂 Birthday dinner — Morena Kitchen', desc:'Window table overlooking illuminated Plaza de Armas. Birthday decoration on the table. Reserved.', type:'birthday',
      place:'Cusco Plaza de Armas',
      facts:['The Plaza de Armas in Cusco was called "Huacaypata" by the Incas — meaning "Place of Weeping" for ceremonies.','The two churches on the plaza (La Catedral and La Compañía) were both built on top of Inca palaces.','La Catedral took 100 years to build (1559–1654) and contains the famous "Last Supper" painting with guinea pig!','The plaza was the location of the most important Inca ceremonies, festivals, and political events.','Under Spanish rule, the plaza was used for public executions — today it is filled with tourists and locals.','Peruvian trucha (trout) is some of the freshest fish you will ever eat — the rivers are ice-cold mountain water.','Morena Kitchen is known for innovative takes on classic Peruvian dishes using local highland ingredients.','A birthday dinner with a Plaza de Armas view is one of the most romantic and memorable restaurant experiences in Peru.','The lights of the plaza in the evening illuminate the cathedral in golden light — an incredible backdrop.','Today has been one of the most extraordinary days of your family\'s life. Happy birthday — cheers to this!']
    },
  ],
  '2026-05-04': [
    { time:'08:30', end:'09:30', name:'Hotel breakfast — slow morning', desc:'Earned rest after Machu Picchu. No rush today.', type:'morning',
      place:'Cusco',
      facts:['Cusco sits at 3,400m — your body is still adjusting after yesterday\'s big adventure.','Take it slow this morning — altitude affects sleep quality and energy levels even on day 4.','A slow Cusco morning with good coffee and a view of the city is genuinely one of life\'s pleasures.','Cusco has a booming specialty coffee scene — Peruvian coffee from the Amazon jungle is world-class.','The morning light in Cusco bounces off the red tile rooftops creating a beautiful warm glow.','Listen for the church bells — Cusco has over 200 churches and many ring their bells in the morning.','Yesterday you did Machu Picchu at sunrise. Today is about soaking in the ancient city at ground level.','The streets of Cusco\'s San Blas neighborhood are so narrow that only one person can walk at a time.','Breakfast at altitude requires more carbohydrates than usual — your body burns more fuel here.','Cusco\'s colonial architecture blends Spanish Baroque with Inca stonework — it exists nowhere else on Earth.']
    },
    { time:'09:30', end:'11:30', name:'Qorikancha — Temple of the Sun', desc:'Sacred Inca temple fused with a Spanish church. 20 soles. Panoramic tower view included.', type:'morning',
      place:'Qorikancha',
      facts:['Qorikancha means "Golden Enclosure" in Quechua — its walls were once covered in 700 solid gold sheets!','The Spanish melted all the gold and sent it to Spain — an act of cultural destruction still mourned today.','The Spanish built the Church of Santo Domingo directly on top of Qorikancha — the Inca walls still support it.','The Inca stonework at Qorikancha survived the 1650 Cusco earthquake perfectly — the Spanish additions crumbled.','This building was the most sacred site in the entire Inca Empire — even more important than Machu Picchu.','Inside were life-size gold statues of past Inca emperors, a solid gold sun disc, and a golden garden.','The curved outer wall of Qorikancha is considered the finest example of Inca stonework in existence.','At the solstice, sunlight enters through a specific window and illuminates the altar exactly — Inca astronomy!','Qorikancha was dedicated to Inti, the Sun God — the Incas believed their emperor was the son of the sun.','Archaeologists are still discovering new chambers and tunnels beneath Qorikancha to this day.']
    },
    { time:'11:30', end:'13:30', name:'Sacsayhuaman fortress', desc:'300-ton stones above Cusco. Kids love the rock formations. 10-min taxi from Qorikancha.', type:'morning',
      place:'Sacsayhuaman',
      facts:['Sacsayhuaman is pronounced "Sexy Woman" by many tourists — actually it means "Satisfied Falcon" in Quechua!','The largest stone in the fortress weighs an estimated 300 tons — heavier than a blue whale!','The stones were quarried from a mountain 20km away and transported without wheels or iron tools.','The fortress walls are built in three parallel zigzag lines — possibly representing Inca lightning or a puma\'s teeth.','From Sacsayhuaman you get the best panoramic view of all of Cusco spread below in the valley.','The annual Inti Raymi (Festival of the Sun) is celebrated here every June 24 with 100,000 spectators.','Kids love Sacsayhuaman because the huge stone terraces are perfect for scrambling and exploring.','The Spanish destroyed much of the upper fortress and used the stones to build Cusco\'s colonial buildings.','Sacsayhuaman\'s construction is estimated to have taken 20,000 workers over 70 years to complete.','The precision of the stonework means not even a razor blade can fit between the perfectly fitted blocks.']
    },
    { time:'13:30', end:'15:00', name:'Lunch — KUSYKAY', desc:"Rated 4.9 · 10,000+ reviews · steps from Plaza de Armas. Trucha andina + chicken tacos.", type:'afternoon',
      place:'Cusco Historic Center',
      facts:['Cusco\'s restaurant scene is one of the most exciting in South America — the altitude does not slow the chefs down!','Trucha andina (Andean trout) in Cusco comes from high-altitude rivers and lakes — exceptionally fresh.','Peruvian chicken (pollo a la brasa) is marinated in 13 herbs and spices and slow-roasted — a national obsession.','The Plaza de Armas is surrounded by colonial arcades (porticoes) where people have eaten and socialized for 500 years.','Peru has been voted World\'s Best Culinary Destination more times than any other country.','Ají de gallina (creamy yellow chilli chicken) is the ultimate Cusco comfort food — try it if you see it!','Chicha morada (purple corn drink) is made from purple corn, cinnamon, clove, and lime — incredibly refreshing.','The culinary scene in Cusco blends 500-year-old Andean ingredients with modern techniques.','Choclo (giant corn) from the Sacred Valley is served everywhere in Cusco — the kernels are the size of teeth!','A good meal in Cusco overlooking the plaza costs less than a mediocre meal in most US cities.']
    },
    { time:'15:00', end:'17:30', name:'San Pedro Market + San Blas', desc:'Local market and cobblestone neighborhood. Alpaca wool souvenirs. City viewpoint.', type:'afternoon',
      place:'San Pedro Market & San Blas',
      facts:['San Pedro Market is the real Cusco — not tourist-facing, genuinely where locals shop every day.','The market has over 200 stalls selling everything from fresh alpaca meat to exotic jungle fruits.','Camu camu from the Amazon jungle is sold here — it has 60x more Vitamin C than an orange!','San Blas neighborhood is the artisan quarter of Cusco — woodcarvers, textile weavers, and silversmiths.','The San Blas viewpoint gives one of the best views over Cusco\'s red-tiled rooftops and surrounding mountains.','Alpaca products are the best souvenirs from Cusco — they last decades and get softer with each wash.','Real vs fake alpaca test: real alpaca is slightly slippery and cool to the touch, fake is rough and warm.','San Blas church is tiny and perfectly preserved — inside is one of the most ornate altars in Peru.','The cobblestone streets of San Blas are original Inca pathways — you are walking where Inca nobles walked.','Artisans in San Blas use the same wood-carving techniques brought to Peru by Spanish missionaries in the 1600s.']
    },
    { time:'17:30', end:'19:30', name:'Optional: Hotel spa', desc:'Birthday extension massage. Book through the hotel the night before.', type:'afternoon',
      place:'Cusco',
      facts:['A massage at altitude feels twice as effective — your muscles are more relaxed from the thin air.','Peruvian spa treatments often use local ingredients: quinoa scrubs, coca leaf wraps, and Andean herbal oils.','A traditional Andean massage uses hot stones heated in Andean salt water — incredibly soothing.','After Machu Picchu yesterday and ruins today, your legs genuinely deserve a massage!','Cusco\'s hotel spas are world-class and much more affordable than equivalent spas in the US or Europe.','A birthday massage the day after Machu Picchu is one of the most indulgent travel experiences imaginable.','The altitude means you are burning 20–30% more calories than at sea level — you\'ve earned the treat!','Many Cusco spas offer couples treatments as well as family packages suitable for all ages.','Andean hot stone massage uses volcanic stones from the nearby Sacred Valley — completely natural.','This is the last relaxed evening in Peru — enjoy every minute of it.']
    },
    { time:'19:30', end:'21:30', name:'Farewell dinner — Chulls', desc:"Rated 4.9. Ají de gallina (creamy chicken stew). Chicha Morada for the kid.", type:'evening',
      place:'Cusco',
      facts:['Ají de gallina is made with shredded chicken in a creamy yellow chilli sauce — the ultimate Peruvian comfort food.','The dish is thickened with bread and walnuts soaked in milk — a colonial-era recipe still perfect today.','Chicha Morada (purple corn drink) is non-alcoholic, naturally sweet, and loved by children throughout Peru.','Cusco has thousands of restaurants but only a handful truly combine quality, authenticity, and atmosphere.','This is your last dinner in Peru — Machu Picchu, Sacred Valley, Aguas Calientes, and Cusco all done.','Peruvian desserts include picarones (sweet potato doughnuts with syrup) and mazamorra morada (purple corn pudding).','The perfect way to end a Peru trip: a cozy courtyard restaurant, great food, and the family together.','Tomorrow you fly to Bogota — a completely different country, culture, and altitude (still high!).','Toast to the trip with a pisco sour (adults) and chicha morada (the 8-year-old)!','The memories made this week — Machu Picchu on a birthday, llamas, trains, thermal baths — will last forever.']
    },
  ],
  '2026-05-05': [
    { time:'09:00', end:'12:00', name:'Hotel breakfast + last Cusco morning', desc:'Check out by 12pm. Last coffee, final stroll around Plaza de Armas.', type:'morning',
      place:'Cusco',
      facts:['Your last morning in Cusco — take it in slowly. The Plaza de Armas feels different when you know you are leaving.','Cusco\'s altitude of 3,400m will be missed in one strange way: food tastes more intense at altitude!','The Cathedral on the Plaza de Armas took 100 years to build and houses 400 pieces of colonial art.','Peruvian coffee is grown in the Amazon jungle region called "the eyebrow of the jungle" — try one last cup!','The famous 12-angled stone is a 5-minute walk from the plaza — a perfect last Cusco photo stop.','The Inca walls along Hatunrumiyoc Street are the most photographed stones in all of Cusco.','Cusco\'s altitude means your body has been working harder than normal all week — you deserve the rest on the flight.','Buy your last Peruvian snacks at San Pedro Market — chicha morada powder and quinoa travel well.','Look up at the mountains surrounding Cusco one last time — Sacsayhuaman fortress is visible from the plaza.','Peru has been the most visited country in South America for several consecutive years — now you know why.']
    },
    { time:'12:00', end:'14:00', name:'Relax + last Cusco stroll', desc:'Bags stored at hotel. Light lunch near Plaza de Armas. Last look at Cusco — soak it all in.', type:'afternoon',
      place:'Cusco',
      facts:['The Plaza de Armas fountain has been in the same location since Spanish colonial times.','Cusco\'s elevation means the sky here looks a deeper shade of blue than anywhere at sea level.','The mountains surrounding Cusco have Inca terraces on them that are still used for farming today.','You can buy fresh coca leaves at any market for a few soles — perfectly legal and locally chewed for energy.','The San Blas neighborhood\'s viewpoint gives you one last spectacular panorama over the city.','Cusco receives about 2 million tourists per year but the old town never feels overcrowded — it is well managed.','The air in Cusco smells of wood smoke from cooking fires, incense from churches, and mountain herbs.','Local women in traditional dress (with llamas for photos) are a staple of the Plaza de Armas scene.','The last stroll through Cusco with no agenda — just wandering — is often the most memorable part of any trip.','Goodbye Cusco — the Navel of the World. Until next time.']
    },
    { time:'14:00', end:'17:10', name:'Head to Cusco Airport (CUZ)', desc:'Arrive 3 hrs before departure. AV104 check-in. Last look at the Andes!', type:'logistics',
      place:'Cusco Airport',
      facts:['Cusco Airport is one of the few airports in the world where you fly out over a mountain range immediately after takeoff.','The view from a plane leaving Cusco shows the Sacred Valley, Andean peaks, and if clear — Machu Picchu!','AV104 connects the ancient Inca capital to the modern Colombian capital in under 4 hours.','Cusco airport sits at 3,399m — take-off requires much more runway than airports at sea level.','Peruvian airports sell excellent local products: quinoa, coffee, pisco, and alpaca goods at fair prices.','This is your last look at the Andes from the ground for now — look at those peaks!','The flight south to Bogota takes you over some of the wildest and most remote terrain in South America.','Bogota sits at 2,600m altitude — still high but lower than Cusco, you will feel the difference.','Colombia is famous for its coffee, street food, colonial architecture, and incredibly warm people.','You are leaving one ancient capital (Cusco) for another incredible city (Bogota) — the adventure continues!']
    },
    { time:'17:10', end:'20:00', name:'AV104 — Cusco to Bogota', desc:'Departs 5:10pm. ~3.5 hr flight. Arrives El Dorado International Airport ~8pm.', type:'logistics',
      place:'In the Air',
      facts:['The flight from Cusco to Bogota crosses the entire Amazon basin — look down and see endless jungle!','You are flying from Peru (Pacific coast country) to Colombia (Caribbean + Pacific coast country).','Bogota is the third-highest capital city in the world at 2,600m — after Quito and La Paz.','Colombia has gone through a remarkable transformation — it is now one of South America\'s top travel destinations.','Bogota\'s elevation means the climate is spring-like year-round — locals call it "the eternal spring."','The flight crosses into Colombia over some of the world\'s most biodiverse cloud forests.','Colombia is the only country in South America with coastlines on both the Pacific Ocean AND the Caribbean Sea.','Bogota has more museums per capita than almost any other city in Latin America.','Avianca is Colombia\'s flag carrier and one of the oldest airlines in the Americas — founded in 1919!','You have been to Cusco, Sacred Valley, Aguas Calientes, and Machu Picchu. Now Bogota. What a trip!']
    },
    { time:'20:00', end:'22:00', name:'Arrive Bogota + Hilton Garden Inn', desc:'Call hotel from arrivals for the free airport shuttle. Check in. Spa whirlpool open late.', type:'logistics',
      place:'Bogota, Colombia',
      facts:['El Dorado International Airport is named after the legendary city of gold that Spanish conquistadors searched for.','Bogota\'s population is 8 million people — one of the largest cities in South America.','The city has an incredible cycle lane network called "Ciclovía" — 120km of dedicated bike paths.','Every Sunday in Bogota, 120km of roads are closed to cars and opened to cyclists — 2 million people participate!','Bogota has transformed dramatically since 2000 — it is now one of the most innovative cities in the world.','The Hilton Garden Inn is right next to the airport — perfect for a late arrival and early morning city trip.','Bogota sits on a high plateau called the "Sabana" (savanna) surrounded by mountains on the east.','The city\'s Gold Museum holds 55,000 pre-Colombian gold pieces — the largest gold collection in the world!','Bogota\'s street food scene features arepas, empanadas, and bandeja paisa — all delicious.','The temperature in Bogota is around 14°C (57°F) year-round — bring a light jacket for the morning!']
    },
  ],
  '2026-05-06': [
    { time:'08:00', end:'09:00', name:'Breakfast + leave bags at hotel', desc:'All luggage stored at reception. Light daypack only. ~6 hrs in the city.', type:'morning',
      place:'Bogota, Colombia',
      facts:['Bogota\'s breakfast culture is incredible — try a changua (milk soup with egg) or an arepa con queso!','Colombian coffee at breakfast in Colombia is the real deal — the country produces some of the world\'s finest beans.','Bogota is a city of 8 million at 2,600m altitude — traffic can be heavy, so Uber is always the smart choice.','The city is divided into "estratos" (economic zones) 1–6 — tourists mainly visit zonas 1–4.','Bogota\'s Zona Rosa (Pink Zone) is the upscale dining and shopping area — safe, walkable, and vibrant.','Today you have about 6–7 hours to explore before the evening flight home to Chicago.','The Hilton Garden Inn holds luggage all day after checkout — essential for a transit-day city visit.','The famous Bogota Gold Museum (Museo del Oro) is just 20 minutes from the hotel — incredible if you have time.','Bogota\'s street art scene is internationally famous — La Candelaria has murals on almost every wall.','Colombia\'s national sport is cycling — Colombians have won the Tour de France multiple times!']
    },
    { time:'09:00', end:'11:30', name:'Monserrate cable car', desc:'Panoramic Bogota views from 3,150m. Priority pass purchased. Cable car up, funicular down.', type:'morning',
      place:'Cerro Monserrate, Bogota',
      facts:['Monserrate peak stands at 3,152m — from the top you see all of Bogota spread across the Sabana below.','The white church at the top (El Señor Caído) is one of the most visited pilgrimage sites in Colombia.','The cable car covers 854m of elevation in about 5 minutes — one of the most thrilling urban cable car rides.','On a clear day you can see the entire city of Bogota from Monserrate — 8 million people below!','The funicular (rack railway) that runs parallel to the cable car has been operating since 1929.','Monserrate is visited by over 3 million people per year — buy the priority pass to skip the 2-hour queue!','The peak is often in the clouds — if it is clear in the morning, go immediately! Clouds roll in by noon.','Local vendors at the top sell fresh strawberries with cream — a Bogota tradition at Monserrate.','The view shows the Andes mountain range extending in both directions — you can see forever on a clear day.','Your 8-year-old will love the cable car ride — the view looking back over the city is breathtaking.']
    },
    { time:'11:30', end:'12:00', name:'Travel to La Candelaria', desc:'Uber from Monserrate to the historic district (~20 min). Good time to grab a quick snack.', type:'logistics',
      place:'Bogota',
      facts:['La Candelaria is Bogota\'s historic heart — founded by the Spanish in 1538, it is one of the oldest neighborhoods in the Americas.','The neighborhood sits at the foot of Monserrate mountain — dramatic mountains in the backdrop of every street photo.','Uber in Bogota is safe, reliable, and very affordable compared to taxis.','The streets of La Candelaria are lined with colonial buildings painted in vivid yellow, red, and blue.','This neighborhood is home to most of Bogota\'s major museums: Gold Museum, Botero Museum, National Museum.','Street food vendors in La Candelaria sell empanadas de pipián (pumpkin seed filling) — a Bogota specialty.','The gold museum in La Candelaria has 55,000 pre-Colombian gold pieces — the most gold artifacts in one museum.','Fernando Botero, Colombia\'s most famous artist, donated 123 of his sculptures and paintings to Bogota — many are here.','The streets of La Candelaria are safe during the day when busy — follow your guide\'s advice on where to walk.','Bogota receives about 4 million tourists per year — it is one of South America\'s fastest-growing destinations.']
    },
    { time:'12:00', end:'14:30', name:'La Candelaria historic district', desc:'Colonial streets, Bolivar Plaza, Chorro de Quevedo. Street performers, chicha vendors.', type:'afternoon',
      place:'La Candelaria, Bogota',
      facts:['Plaza Bolivar is the heart of La Candelaria — surrounded by the Capitol, City Hall, Supreme Court, and Cathedral.','Simon Bolivar liberated Colombia, Venezuela, Ecuador, Peru, and Bolivia from Spanish rule — all on horseback.','The pigeons in Plaza Bolivar are legendary — locals say there are more pigeons than people in Bogota!','Chorro de Quevedo plaza is where Bogota was officially founded on August 6, 1538 by Gonzalo Jiménez de Quesada.','The street art murals in La Candelaria are world-famous — some cover entire 10-story buildings.','Colombian empanadas are different from Peruvian ones — fried, filled with meat or chicken, and served with hot sauce.','The National Museum of Colombia (Museo Nacional) in La Candelaria is the oldest museum in Colombia.','Botero Museum is completely free and contains original paintings and sculptures by Colombia\'s most famous artist.','Street performers in La Candelaria include tango dancers, magicians, and traditional cumbia drummers.','After La Candelaria, you will have seen: Machu Picchu, Cusco, Aguas Calientes, Bogota — what a trip!']
    },
    { time:'14:30', end:'17:00', name:'Return to hotel + collect bags', desc:'Uber back to Hilton. Collect luggage. Head to El Dorado airport.', type:'logistics',
      place:'Bogota',
      facts:['El Dorado Airport is Colombia\'s busiest airport — allow 3 full hours for international check-in.','The airport has excellent duty-free shopping: Colombian coffee, emeralds, rum, and handicrafts.','Colombian emeralds are considered the finest in the world — 70–90% of global emerald production comes from Colombia.','Juan Valdez coffee shop in the airport sells fresh-brewed Colombian single-origin coffee — a must before boarding.','AV262 will fly you back to Chicago O\'Hare overnight — the same Avianca you flew down on.','You are heading home from one of the most incredible travel itineraries possible in South America.','The whole family has now seen: Cusco, Sacred Valley, Aguas Calientes, Machu Picchu, and Bogota. Incredible!','Buy Colombian ground coffee at the airport — it makes an amazing souvenir that people actually use.','The flight back to Chicago will feel very different from the excited anticipation of the outbound journey.','Three countries in one trip: USA, Peru, Colombia. With an 8-year-old. On a birthday. Outstanding.']
    },
    { time:'17:00', end:'20:00', name:'El Dorado Airport — AV262', desc:'Arrive 3 hrs before departure. Buy Colombian coffee at duty-free!', type:'logistics',
      place:'El Dorado Airport, Bogota',
      facts:['El Dorado Airport is named after the legendary lost city of gold that Spanish conquistadors hunted for centuries.','The airport serves about 35 million passengers per year — one of the busiest in Latin America.','Juan Valdez coffee (Colombia\'s iconic brand) has shops throughout the airport — buy beans to take home!','Colombian emeralds sold in airport shops are certified conflict-free and come with authentication documents.','Avianca flight AV262 will arrive in Chicago — completing the full loop: ORD → BOG → CUZ → BOG → ORD.','The overnight flight to Chicago will cross the Gulf of Mexico and the southeastern United States.','You will land in Chicago on May 6 or 7 depending on departure time — a small adventure in time zones!','The trip cost, memories, and experiences will be talked about in your family for the rest of your lives.','The 8-year-old has now seen: a Wonder of the World, cloud forests, Andean ruins, and a colonial capital.','Safe travels home — what an extraordinary week. Peru + Colombia = unforgettable.']
    },
    { time:'20:00', end:'23:59', name:'AV262 — Bogota to Chicago (ORD)', desc:'Homebound. Trip complete — Machu Picchu on a birthday, Peru + Bogota. Unforgettable.', type:'logistics',
      place:'In the Air — Heading Home',
      facts:['You are flying home from South America after one of the most incredible family trips possible.','Total distance traveled this week: approximately 12,000 km — nearly halfway around the Earth!','You have been to: Chicago → Bogota → Cusco → Ollantaytambo → Aguas Calientes → Machu Picchu → Cusco → Bogota → Chicago.','Your 8-year-old has stood at a Wonder of the World, ridden a panoramic train through cloud forest, and soaked in natural hot springs.','The birthday girl celebrated at Machu Picchu at sunrise — there are very few birthdays more epic than that.','Machu Picchu, Qorikancha, Sacsayhuaman, Ollantaytambo, Monserrate — 5 extraordinary historical sites in 6 days.','You ate trucha andina, ají de gallina, lomo saltado, Andean ceviche, and Colombian empanadas.','You rode the Vistadome Observatory train, a cable car over Bogota, and a bus with 13 hairpin turns up a mountain.','The altitude challenges, the 4:30am wake-up, the llamas, the thermal baths — all part of the story now.','Welcome home, family. That was truly extraordinary. Start planning the next one!']
    },
  ],
};

const TRIP_CONFIG = {
  tripStart: '2026-05-01T11:20:00',
  tripEnd:   '2026-05-07T00:00:00',
  birthdayDate: '2026-05-03',
  departureDate: '2026-04-30',
  landingCusco: '2026-05-01T11:20:00',
  departureCity: "O'Hare (ORD)",
  timezone: 'America/Lima',
};

const DAY_LABELS = {
  '2026-05-01': 'Day 1 — Arrival in Peru',
  '2026-05-02': 'Day 2 — Ticket Day, Aguas Calientes',
  '2026-05-03': 'Day 3 — Machu Picchu Birthday',
  '2026-05-04': 'Day 4 — Cusco Exploration',
  '2026-05-05': 'Day 5 — Departing Peru',
  '2026-05-06': 'Day 6 — Bogota & Home',
};

const TYPE_CONFIG = {
  logistics: { label: 'Transit',      cls: 'tag-logistics' },
  morning:   { label: 'Morning',      cls: 'tag-morning'   },
  afternoon: { label: 'Afternoon',    cls: 'tag-afternoon' },
  evening:   { label: 'Evening',      cls: 'tag-evening'   },
  birthday:  { label: '🎂 Birthday',  cls: 'tag-birthday'  },
  priority:  { label: '⚠️ Priority',  cls: 'tag-priority'  },
};

function toMins(t) {
  const [h, m] = t.split(':').map(Number);
  return h * 60 + m;
}

function getPeruTime() {
  return new Date(new Date().toLocaleString('en-US', { timeZone: TRIP_CONFIG.timezone }));
}

function getTodayKey() {
  const now = getPeruTime();
  return `${now.getFullYear()}-${String(now.getMonth()+1).padStart(2,'0')}-${String(now.getDate()).padStart(2,'0')}`;
}

function fmtCountdown(ms) {
  const s = Math.floor(ms / 1000);
  return {
    d: Math.floor(s / 86400),
    h: Math.floor((s % 86400) / 3600),
    m: Math.floor((s % 3600) / 60),
    s: s % 60,
  };
}

function resolveActivity(dateKey, nowMins) {
  const items = TRIP_EVENTS[dateKey] || [];
  let currentIdx = -1, nextIdx = -1;
  for (let i = 0; i < items.length; i++) {
    const s = toMins(items[i].time), e = toMins(items[i].end);
    if (nowMins >= s && nowMins < e) { currentIdx = i; break; }
    if (nowMins < s) { nextIdx = i; break; }
  }
  if (currentIdx === -1 && nextIdx === -1) currentIdx = items.length - 1;

  const current = currentIdx >= 0 ? items[currentIdx] : null;
  let nextWithinHour = null;
  const checkNext = current ? items[currentIdx + 1] : (nextIdx >= 0 ? items[nextIdx] : null);
  if (checkNext && toMins(checkNext.time) - nowMins <= 60) nextWithinHour = checkNext;

  return { current, nextWithinHour, items };
}
